// Generated by https://quicktype.io

export interface PropertyDayHistoricI {
  propertyId: number;
  historicConsumption: DayHistoricConsumptionI[];
  historicProduction: DayHistoricProductionI[];
  device: DayHistoricDeviceI[];
}

export interface DayHistoricDeviceI {
  _id: string;
  deviceId: number;
  historicDeviceAttribute: any[];
  name: string;
  priority: number;
  userStatus: number;
  machineStatus: string;
  maxDevicePower: number;
  minDevicePower: number;
  authorized: boolean;
  errorCode: null | string;
  warningCode: null | string;
}

export interface DayHistoricConsumptionI {
  _id: string;
  net: number;
  cleanVat: number;
  batteryPower: number;
  loadPower: number;
  meterPower: number;
  fee: number;
  tip: number;
  flat: number;
  valley: number;
  feeType: number;
  createdAt: string;
}

export interface DayHistoricProductionI {
  _id: string;
  net: number;
  cleanVat: number;
  pvPower: number;
  createdAt: string;
}
